<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ConfirmExtractionRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'master' => ['required', 'array'],

            'master.order_code' => ['nullable', 'string', 'max:255'],
            'master.quotation_number' => ['nullable', 'numeric'],
            'master.quotation_branch_number' => ['nullable', 'numeric'],
            'master.quotation_date' => ['nullable', 'date'],
            'master.handling_office' => ['nullable', 'string', 'max:255'],
            'master.handling_office_code' => ['nullable', 'string', 'max:255'],
            'master.handling_staff_name' => ['nullable', 'string', 'max:255'],
            'master.handling_staff_code' => ['nullable', 'string', 'max:255'],
            'master.customer_code' => ['nullable', 'string', 'max:255'],
            'master.customer_name' => ['nullable', 'string', 'max:255'],
            'master.customer_zip_code' => ['nullable', 'string', 'max:255'],
            'master.customer_prefecture' => ['nullable', 'string', 'max:255'],
            'master.customer_address1' => ['nullable', 'string', 'max:255'],
            'master.customer_address2' => ['nullable', 'string', 'max:255'],
            'master.customer_address3' => ['nullable', 'string', 'max:255'],
            'master.billing_code' => ['nullable', 'string', 'max:255'],
            'master.billing_name' => ['nullable', 'string', 'max:255'],
            'master.payment_terms' => ['nullable', 'string', 'max:255'],
            'master.billing_closing_date' => ['nullable', 'string', 'max:255'],
            'master.scheduled_payment' => ['nullable', 'date'],
            'master.tax_calculation_class' => ['nullable', 'string', 'max:255'],
            'master.contract_office' => ['nullable', 'string', 'max:255'],
            'master.contract_office_code' => ['nullable', 'string', 'max:255'],
            'master.staff_name' => ['nullable', 'string', 'max:255'],
            'master.staff_code' => ['nullable', 'string', 'max:255'],
            'master.payment_destination_name' => ['nullable', 'string', 'max:255'],
            'master.payment_destination_code' => ['nullable', 'string', 'max:255'],
            'master.staff_zip_code' => ['nullable', 'string', 'max:255'],
            'master.staff_prefecture' => ['nullable', 'string', 'max:10'],
            'master.staff_address1' => ['nullable', 'string', 'max:255'],
            'master.staff_address2' => ['nullable', 'string', 'max:255'],
            'master.staff_address3' => ['nullable', 'string', 'max:255'],
            'master.payment_conditions' => ['nullable', 'string', 'max:255'],
            'master.payment_closing_date' => ['nullable', 'string', 'max:255'],
            'master.scheduled_payment_date' => ['nullable', 'date'],
            'master.staff_tax_classification' => ['nullable', 'string', 'max:255'],
            'master.planned_service_date' => ['nullable', 'date'],
            'master.planned_service_time' => ['nullable', 'string', 'max:255'],
            'master.planned_users_count' => ['nullable', 'numeric'],
            'master.user_information' => ['nullable', 'string'],
            'master.service_area_class' => ['nullable', 'string', 'max:255'],
            'master.service_location' => ['nullable', 'string', 'max:255'],
            'master.desired_staff_count' => ['nullable', 'numeric'],
            'master.service_classification' => ['nullable', 'string', 'max:255'],
            'master.required_qualifications' => ['nullable', 'string'],
            'master.subject' => ['nullable', 'string', 'max:255'],
            'master.delivery_date' => ['nullable', 'date'],
            'master.expiration_date' => ['nullable', 'date'],
            'master.service_type' => ['nullable', 'string', 'max:255'],
            'master.branch_number' => ['nullable', 'string', 'max:255'],
            'master.total_quantity' => ['nullable', 'numeric'],
            'master.total_amount' => ['nullable', 'numeric', 'min:0'],
            'master.total_base_cost' => ['nullable', 'numeric'],
            'master.total_gross_profit' => ['nullable', 'numeric'],
            'master.total_gross_profit_rate' => ['nullable', 'numeric'],
            'master.total_consumption_tax' => ['nullable', 'numeric'],
            'master.base_cost' => ['nullable', 'numeric'],
            'master.advance_payment' => ['nullable', 'numeric'],
            'master.transportation_cost' => ['nullable', 'numeric'],
            'master.billing_information' => ['nullable', 'string'],
            'master.accepted_case' => ['nullable', 'string'],
            'master.tickets' => ['nullable', 'string'],
            'master.report_remarks' => ['nullable', 'string'],
            'master.staff_memo' => ['nullable', 'string'],
            'master.sales_method' => ['nullable', 'string', 'max:255'],
            'master.credit_base_date' => ['nullable', 'date'],
            'master.collection_type' => ['nullable', 'string', 'max:255'],
            'master.notes' => ['nullable', 'string'],

            'master.same_day_request' => ['nullable', 'boolean'],
            'master.extension' => ['nullable', 'boolean'],
            'master.english_support' => ['nullable', 'string', 'max:255'],
            'master.is_sameday_request' => ['nullable', 'boolean'],
            'master.is_sameday_cancellation' => ['nullable', 'boolean'],
            'master.is_pickup_up_drop' => ['nullable', 'boolean'],
            'master.is_pickup_drop_preschooler' => ['nullable', 'boolean'],
            'master.is_bathing' => ['nullable', 'boolean'],
            'master.is_english_a' => ['nullable', 'boolean'],
            'master.is_english_b' => ['nullable', 'boolean'],
            'master.is_outdoor' => ['nullable', 'boolean'],

            'master.required_start' => ['nullable', 'string', 'max:255'],
            'master.required_end' => ['nullable', 'string', 'max:255'],
            'master.extension_time_from' => ['nullable', 'string', 'max:255'],
            'master.extension_time_to' => ['nullable', 'string', 'max:255'],

            'items' => ['nullable', 'array'],
            'items.*.line_number' => ['nullable', 'numeric'],
            'items.*.line_processing_type' => ['nullable', 'string', 'max:255'],
            'items.*.service_code' => ['nullable', 'string', 'max:255'],
            'items.*.service_name1' => ['nullable', 'string', 'max:255'],
            'items.*.service_name2' => ['nullable', 'string', 'max:255'],
            'items.*.unit' => ['nullable', 'string', 'max:255'],
            'items.*.start_time' => ['nullable', 'string', 'max:255'],
            'items.*.end_time' => ['nullable', 'string', 'max:255'],
            'items.*.duration' => ['nullable', 'string', 'max:255'],
            'items.*.minutes' => ['nullable', 'numeric'],
            'items.*.quantity' => ['nullable', 'numeric', 'min:0'],
            'items.*.tax_classification' => ['nullable', 'string', 'max:255'],
            'items.*.tax_rate' => ['nullable', 'numeric'],
            'items.*.unit_price' => ['nullable', 'numeric', 'min:0'],
            'items.*.amount' => ['nullable', 'numeric'],
            'items.*.base_unit_cost' => ['nullable', 'numeric'],
            'items.*.base_cost' => ['nullable', 'numeric'],
            'items.*.gross_profit' => ['nullable', 'numeric'],
            'items.*.gross_profit_rate' => ['nullable', 'numeric'],
            'items.*.consumption_tax' => ['nullable', 'numeric'],
            'items.*.summary' => ['nullable', 'string'],
            'items.*.item_name' => ['nullable', 'string', 'max:255'],
            'items.*.item_code' => ['nullable', 'string', 'max:255'],
            'field_confidence' => ['nullable', 'array'],
        ];
    }
}
