<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class OrderMaster extends Model
{
    use HasFactory;

    protected $fillable = [
        'source_file_path',
        'original_filename',
        'customer_name',
        'total_amount',
        'raw_ocr_text',
        'llm_raw_response',
        'field_confidence',
        'llm_provider',
        'status',
        'notes',

        'order_code',
        'quotation_date',
        'status_update_date',
        'handling_office_code',
        'handling_office',
        'handling_staff_code',
        'handling_staff_name',
        'customer_code',
        'billing_code',
        'billing_name',
        'customer_zip_code',
        'customer_prefecture',
        'customer_address1',
        'customer_address2',
        'customer_address3',
        'payment_terms',
        'billing_closing_date',
        'scheduled_payment',
        'tax_calculation_class',
        'contract_office_code',
        'contract_office',
        'staff_name',
        'payment_destination_code',
        'payment_destination_name',
        'staff_zip_code',
        'staff_prefecture',
        'staff_address1',
        'staff_address2',
        'staff_address3',
        'payment_conditions',
        'payment_closing_date',
        'scheduled_payment_date',
        'staff_tax_classification',
        'planned_service_date',
        'planned_users_count',
        'user_information',
        'service_area_class',
        'service_location',
        'desired_staff_count',
        'service_classification',
        'required_qualifications',
        'subject',
        'delivery_date',
        'expiration_date',
        'registered_by',
        'last_updated_by',
        'request_status',
        'request_date_time',
        'request_approved_by',
        'shift_status',
        'shift_date_time',
        'shift_approved_by',
        'order_confirmed_Status',
        'order_confirmed_datetime',
        'order_confirmed_by',
        'sales_confirmed_status',
        'sales_confirmed_datetime',
        'sales_confirmed_by',
        'bill_closed_status',
        'bill_closed_datetime',
        'bill_closed_confirmed_by',
        'payment_status',
        'payment_datetime',
        'payment_confirmed_by',
        'quotation_output_class',
        'order_flg',
        'service_type',
        'staff_id',
        'required_start',
        'required_end',
        'total_quantity',
        'total_base_cost',
        'total_gross_profit',
        'total_gross_profit_rate',
        'total_consumption_tax',
        'extension_time_from',
        'extension_time_to',
        'billing_information',
        'accepted_case',
        'tickets',
        'report_remarks',
        'customer_id',
        'staff_information',
        'advance_payment',
        'transportation_cost',
        'bill_transaction_code',
        'payment_transaction_code',
        'branch_number',
        'extended_start_time',
        'extended_end_time',
        'enter_start_time',
        'enter_end_time',
        'reference_time',
        'extended_time_input',
        'night_time_input',
        'late_night_input',
        'day_of_week_proc',
        'same_day_request',
        'extension',
        'english_support',
        'outdoor1_start_time',
        'outdoor1_end_time',
        'outdoor2_start_time',
        'outdoor2_end_time',
        'base_cost',
        'staff_memo',
        'sales_method',
        'credit_base_date',
        'collection_type',
        'is_sameday_request',
        'is_sameday_cancellation',
        'is_pickup_up_drop',
        'is_pickup_drop_preschooler',
        'is_bathing',
        'is_english_a',
        'is_english_b',
        'is_outdoor',
        'extra_basic_hour',
        'basic_time',
        'housework_1_start_time',
        'housework_2_start_time',
        'housework_1_completion_time',
        'housework_2_end_time',
        'number_of_transfers',
        'number_of_baths',
        'number_of_pick_ups',
        'house_work_time',
        'outdoor_time',
    ];

    protected $casts = [
        'quotation_date' => 'date',
        'planned_service_date' => 'date',
        'delivery_date' => 'date',
        'expiration_date' => 'date',
        'scheduled_payment' => 'date',
        'scheduled_payment_date' => 'date',
        'credit_base_date' => 'date',
        'total_amount' => 'decimal:2',
        'total_base_cost' => 'decimal:2',
        'total_gross_profit' => 'decimal:2',
        'total_gross_profit_rate' => 'decimal:2',
        'total_consumption_tax' => 'decimal:2',
        'total_quantity' => 'decimal:2',
        'base_cost' => 'decimal:2',
        'advance_payment' => 'integer',
        'transportation_cost' => 'integer',
        'required_start' => 'string',
        'required_end' => 'string',
        'extension_time_from' => 'string',
        'extension_time_to' => 'string',
        'extended_start_time' => 'string',
        'extended_end_time' => 'string',
        'enter_start_time' => 'string',
        'enter_end_time' => 'string',
        'reference_time' => 'string',
        'extended_time_input' => 'string',
        'night_time_input' => 'string',
        'late_night_input' => 'string',
        'outdoor1_start_time' => 'string',
        'outdoor1_end_time' => 'string',
        'outdoor2_start_time' => 'string',
        'outdoor2_end_time' => 'string',
        'extra_basic_hour' => 'string',
        'basic_time' => 'string',
        'housework_1_start_time' => 'string',
        'housework_2_start_time' => 'string',
        'housework_1_completion_time' => 'string',
        'housework_2_end_time' => 'string',
        'house_work_time' => 'string',
        'outdoor_time' => 'string',
        'order_flg' => 'boolean',
        'same_day_request' => 'boolean',
        'extension' => 'boolean',
        'is_sameday_request' => 'boolean',
        'is_sameday_cancellation' => 'boolean',
        'is_pickup_up_drop' => 'boolean',
        'is_pickup_drop_preschooler' => 'boolean',
        'is_bathing' => 'boolean',
        'is_english_a' => 'boolean',
        'is_english_b' => 'boolean',
        'is_outdoor' => 'boolean',
        'llm_raw_response' => 'array',
        'field_confidence' => 'array',
        'request_date_time' => 'datetime',
        'shift_date_time' => 'datetime',
        'order_confirmed_datetime' => 'datetime',
        'sales_confirmed_datetime' => 'datetime',
        'bill_closed_datetime' => 'datetime',
        'payment_datetime' => 'datetime',
        'status_update_date' => 'datetime',
    ];

    public function details(): HasMany
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function recalculateTotal(): void
    {
        $this->total_amount = $this->details()->sum('amount');
        $this->save();
    }

    public function assertEditable(): void
    {
        if ($this->status === 'confirmed') {
            abort(409, 'This order is confirmed. Reopen it before editing.');
        }
    }
}
